# SPDX-License-Identifier: GPL-2.0

# Linux kernel module xloop
obj-$(CONFIG_BLK_DEV_XLOOP)               += xloop.o
xloop-y                                   += xloop_main.o xloop_file_fmt.o

# Linux kernel module loop_file_fmt_raw
obj-$(CONFIG_BLK_DEV_XLOOP_FILE_FMT_RAW)  += xloop_file_fmt_raw.o

# Linux kernel module loop_file_fmt_qcow
obj-$(CONFIG_BLK_DEV_XLOOP_FILE_FMT_QCOW) += xloop_file_fmt_qcow.o
xloop_file_fmt_qcow-y                     += xloop_file_fmt_qcow_main.o xloop_file_fmt_qcow_cluster.o xloop_file_fmt_qcow_cache.o