name: Build xloop program

on:
  push:
    branches:
      - master
  pull_request:
  release:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: debug [default] on Ubuntu 20.04
            build-os: ubuntu-20.04
            build-type: "Debug"
          - name: release [default] on Ubuntu 20.04
            build-os: ubuntu-20.04
            build-type: "Release"
    name: Build xloop ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.build-os }}
    steps:
      - name: Install xloop dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq make \
                                      clang-format \
                                      linux-headers-generic \
                                      libcap-dev \
                                      rpm
      - name: Checkout xloop repository
        uses: actions/checkout@v2
      - name: Fetch xloop repository tags
        run: git fetch --prune --unshallow
      - name: Configure xloop build
        run: |
          cmake -B ${{ github.workspace }}/build \
                -S ${{ github.workspace }} \
                -D CMAKE_BUILD_TYPE=${{ matrix.config.build-type }}
      - name: Build xloop artifacts
        working-directory: ${{ github.workspace }}/build
        run: make xlosetup
