name: Lint xloop

on:
  push:
    branches:
      - master
  pull_request:
  release:

jobs:
  lint:
    name: Lint xloop
    runs-on: ubuntu-20.04
    steps:
      - name: Install xloop dependencies
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y -qq make \
                                      clang-format \
                                      linux-headers-generic \
                                      libcap-dev \
                                      rpm
      - name: Checkout xloop repository
        uses: actions/checkout@v2
      - name: Fetch xloop repository tags
        run: git fetch --prune --unshallow
      - name: Configure xloop build
        run: |
          cmake -B ${{ github.workspace }}/build \
                -S ${{ github.workspace }}
      - name: Lint xloop artifacts
        working-directory: ${{ github.workspace }}/build
        run: make lint
